version: "3.7"

services:
    nginx:
        image: nginx:latest
        container_name: nginx_container
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - docker-network
        ports:
            - 80:80
            - 443:443
        depends_on:
            - backend_server

    backend_server:    
        build: .
        container_name: backend_container
        volumes:
            - ./app:/backend/app
        networks:
            docker-network:
                aliases:
                    - backend_server
        ports:
            - 8000:8000

networks:
    docker-network:
