name: Build

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/backend.yml

jobs:   
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Deploy to Google Compute Engine
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd noti-summary-questionnaire/backend
          git pull
          docker-compose --env-file .env up --build  -d
